### PR TITLE
Fix attribute errors being created as unknown

### LINKED ISSUE #176: Error decoding issue
This test fails, it should not

```
    #[test]
    fn encode_decode() {
        let event = hex::decode("a30045030000000201c11a62e7dcea02a500820982010301d92710582080e8acda9634f6f745be872b0e5e9b65b1d3624a3ba91c6432143f60e90000020245020000000103f604d92712a301d92710582080e8acda9634f6f745be872b0e5e9b65b1d3624a3ba91c6432143f60e900000204a3003a00015f9001781d4163636f756e742077697468204944207b69647d20756e6b6e6f776e2e02a162696478326d6166666261686b736477617165656e6179793267786b65333268676237617134616f3477743734356c7366733677696a7005c11a62e7dcf5").unwrap();
        let event_log: EventLog = minicbor::decode(&event).unwrap();
        match event_log.content {
            EventInfo::AccountMultisigExecute {
                account,
                token,
                executer,
                response,
            } => {
                assert!(response.data.unwrap_err().is_attribute_specific());
            }
            _ => {}
        }
    }
```

The error code should be `-90001` and NOT `-1`

### PR DESCRIPTION
**Pull request by Denommus**
Attribute errors weren't being created when x <= -10000

## Related Issue

Fixes #176

## Testing

Created encode_decode unit test

## Breaking Changes (if applicable)

Errors with a code <= -10000 are no longer Unknown errors, but AttributeErrors

## Checklist:

- [X] I have read and followed the CONTRIBUTING guidelines for this project.
- [X] I have added or updated tests and they pass.
- [X] I have added or updated documentation and it is accurate.
- [X] I have noted any breaking changes in this module or downstream modules.

### CODE REVIEW

File: src/many-modules/src/_4_events.rs [hunk 1]
```diff
@@ -834,4 +834,18 @@ mod tests {
         assert_eq!(list_returns.nb_events, 1);
         assert_eq!(list_returns.events.len(), 1);
     }
+
+    #[test]
+    fn encode_decode() {
+        let event = hex::decode("a30045030000000201c11a62e7dcea02a500820982010301d92710582080e8acda9634f6f745be872b0e5e9b65b1d3624a3ba91c6432143f60e90000020245020000000103f604d92712a301d92710582080e8acda9634f6f745be872b0e5e9b65b1d3624a3ba91c6432143f60e900000204a3003a00015f9001781d4163636f756e742077697468204944207b69647d20756e6b6e6f776e2e02a162696478326d6166666261686b736477617165656e6179793267786b65333268676237617134616f3477743734356c7366733677696a7005c11a62e7dcf5").unwrap();
```
Comment (fmorency) [inline src/many-modules/src/_4_events.rs:840]: Please make multiple lines with this string

File: src/many-modules/src/_4_events.rs [hunk 2]
```diff
@@ -834,4 +834,18 @@ mod tests {
...
+        let event_log: EventLog = minicbor::decode(&event).unwrap();
+        println!("{:?}", event_log);
```
Comment (fmorency) [inline src/many-modules/src/_4_events.rs:842]: Remove

File: src/many-modules/src/_4_events.rs [hunk 3]
```diff
@@ -834,4 +834,18 @@ mod tests {
...
+        if let EventInfo::AccountMultisigExecute {
+            response,
+            ..
+        } = event_log.content {
+            println!("{:?}", response.data);
```
Comment (fmorency) [inline src/many-modules/src/_4_events.rs:847]: Remove

File: src/many-error/src/error.rs [hunk 4]
```diff
@@ -45,6 +45,8 @@ macro_rules! many_error {
                         $v => Self::$name,
                     )*
                     x if x >= 0 => Self::ApplicationSpecific(x as u32),
+                    // TODO: need to clarify whether `x <= -10000` or `x <= 0 && x % 10000 == 0`
```
Comment (fmorency) [inline src/many-error/src/error.rs:48]: @hansl Yuri was wondering this because the following comment in the code isn't clear enough. Can you shed some light, please? I *think* the following is wrong.

```
    // Negative 10000+ are reserved for attribute specified codes and are defined separately.
    // The method to use these is ATTRIBUTE_ID * -10000.
```

**Review by fmorency — CHANGES_REQUESTED** [review]
Thanks!

File: src/many-error/src/error.rs (hunk 4 above)
Comment (Denommus) [reply src/many-error/src/error.rs:48]: Yeah, we should also update the spec (the file that should describe errors is missing from the spec, btw)

File: src/many-modules/src/_4_events.rs (hunk 1 above)
Comment (Denommus) [reply src/many-modules/src/_4_events.rs]: addressed

File: src/many-error/src/error.rs (hunk 4 above)
Comment (hansl) [reply src/many-error/src/error.rs:48]: The spec specifies the error format for now; that's a deliberate omission. We need to address this at some point, but errors are very general and we'll miss some for sure.

What is defined here is that there is a range of errors for an attribute of `(ATTRIBUTE_ID * -10000 .. (ATTRIBUTE_ID+1) * -10000(`.

Comment (hansl) [reply src/many-error/src/error.rs:48]: So attribute `55` would have the range of error codes `-55000 .. -55999` (inclusive).

**Review by fmorency — APPROVED** [review]
LGTM assuming the `TODO` comment is fixed. Thansk @Denommus !

File: src/many-error/src/error.rs (hunk 4 above)
Comment (Denommus) [reply src/many-error/src/error.rs:48]: Ah, ok, then this PR should be correct.
